name: filtro por paises

on:
  schedule:
    - cron: '00 0 * * *' # Runs every day at 00:00 UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  analizando_datos:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: crear tablas por pais
        run: |
         grep Germany -i companies-all.csv  > companies-germany.csv
         grep kingdom -i companies-all.csv  > companies-kingdom.csv
         grep france -i companies-all.csv  > companies-france.csv

      - name: Commit Results
        if: always()
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git diff --quiet || git stash
          git pull --rebase origin main
          git stash list | grep "stash@{0}" && git stash apply
          git add .
          git diff --cached --exit-code || git commit -m "tabla actualizada" --allow-empty
          git push --force-with-lease origin HEAD:main